### ISSUE TITLE
Question about HoneyPi

### ISSUE THREAD

**Issue by rebelbrew88** [mattymcfatty/HoneyPi#1]
Hey Matt,

I'm new to the honeypot game and recently started using yours for a project in one of my courses (I'm a grad student). First off, I'd like to say thank you for your for putting this out. It was very easy to use and install on my Raspberry Pi and I was able to hit the ground running. My question for you (and I apologize if this can be answered somewhere else, I couldn't seem to find the info) is are the ports, specifically port 23 actually able to be accessed? From what I could read from your Python code, they're just fake ports that are posing as easy targets for port scanners. 

I've had some interesting hits from Russia and China, specifically with people attempting to Telnet in. Is there a password for this port? Or is it just "there" and not really able to be accessed.

Thanks again!
-Reb

**Comment by mattymcfatty** [comment]
Hey Reb--

Great question! I'm thinking about adding some stuff to the readme to lay-out the design of the honeypi to make this clearer. 

So there are 3 main elements that drive the honeypot:

1. Iptables/logging
2. cipherdyne's PSAD tool
3. A simple python script to open up some ports

The honeypi installer sets iptables and logging so PSAD can monitor the network logs and send alerts. PSAD is the real hero here and does all the heavy lifting. My only complaint is it was a little tricky to set up (which is why I started this project).  The python script is not even really required for the project to work. It's main function is to make it look like juicy services are listening (telnet, ftp and vnc). I wanted this to be a "low interaction" honeypot, so the only packet the python script sends out is "I'm VNC" or "I'm Telnet" or "I'm FTP". 

If you're wanting more stuff to be available to attacker on telnet, then your options are to modify the python script here to do more stuff. Alternatively, you could replace mattshonepot.py with a "high interaction telnet honeypot". This one looks pretty good but I haven't tested it:
https://github.com/stamparm/hontel

To make it easy, you could keep PSAD alerting and everything the same and just swap my python honeypot for this one. Not 100% sure that would work, but if keeping it simple is the goal, then this is the route I would try.
